services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    expose:
      - "80"
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: folio_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    depends_on:
      - database

  storybook:
    build:
      context: .
      dockerfile: .storybook/Dockerfile
    ports:
      - "6006:6006"

volumes:
  pg_data:
